#!/bin/bash
# Phase 5 Test: Dashboard Integration
# Tests real-time certification light display

echo "==========================================="
echo "Phase 5: Dashboard Integration"
echo "==========================================="
echo ""

echo "Phase 5 adds real-time certification lights to the dashboard."
echo ""

echo "Dashboard Visualization:"
echo "==========================================="
echo ""
echo "When the scheduler emits events, the dashboard displays them as lights:"
echo ""
echo "ADHD Health Dashboard"
echo "────────────────────────────────────────────────────"
echo ""
echo "■ certification — 3 features [🟢2 🟡1 🔴0]"
echo "──────────────────────────────────────────"
echo "  🟢 cert:stripe-api              Level: 100% | test_pass"
echo "  🟡 cert:openai-api             Level: 60% | downgrade"
echo "→ 🟢 cert:anthropic-api           Level: 100% | upgrade"
echo ""

echo "■ smoke-alarm — 5 features [🟢3 🟡1 🔴1]"
echo "──────────────────────────────────────────"
echo "  🟢 smoke:cluster-1/api-health    [healthy]"
echo "  🟡 smoke:cluster-1/db-replication [degraded]"
echo "  🔴 smoke:cluster-2/gateway        [unhealthy]"
echo ""

echo "Certification Level Color Coding:"
echo "==========================================="
echo ""
echo "  🟢 Green:  Level ≥ 80% (fully certified)"
echo "  🟡 Yellow: Level 40-79% (degraded but functional)"
echo "  🔴 Red:    Level 1-39% (at risk)"
echo "  ⚫ Dark:    Level 0% (revoked/offline)"
echo ""

echo "Real-Time Event Updates:"
echo "==========================================="
echo ""

echo "Test 1: Endpoint passes all tests"
echo "  Scheduler emits: ScheduleEvent{Type:test_pass, CertLevel:100}"
echo "  Dashboard receives: SmokeTestEventMsg"
echo "  Light status: 🟢 Green"
echo "  Details: Level: 100% | test_pass"
echo ""

echo "Test 2: Endpoint fails (1 failure)"
echo "  Scheduler emits: ScheduleEvent{Type:test_fail, CertLevel:80}"
echo "  Light status: 🟢 Green (still)"
echo "  Details: Level: 80% | test_fail"
echo ""

echo "Test 3: Endpoint fails again (2 failures)"
echo "  Scheduler emits: ScheduleEvent{Type:test_fail, CertLevel:60}"
echo "  Light status: 🟡 Yellow"
echo "  Details: Level: 60% | test_fail"
echo ""

echo "Test 4: Endpoint fails third time (downgrade triggered)"
echo "  Scheduler emits: ScheduleEvent{Type:downgrade, CertLevel:40}"
echo "  Light status: 🟡 Yellow"
echo "  Details: Level: 40% | downgrade"
echo ""

echo "Test 5: Endpoint comes back online (1 success)"
echo "  Scheduler emits: ScheduleEvent{Type:test_pass, CertLevel:50}"
echo "  Light status: 🟡 Yellow"
echo "  Details: Level: 50% | test_pass"
echo ""

echo "Test 6: Endpoint continues passing (5 successes, upgrade triggered)"
echo "  Scheduler emits: ScheduleEvent{Type:upgrade, CertLevel:100}"
echo "  Light status: 🟢 Green"
echo "  Details: Level: 100% | upgrade"
echo ""

echo "Integration Points:"
echo "==========================================="
echo ""
echo "1. Scheduler Integration:"
echo "   - Scheduler.Start() begins testing"
echo "   - Emits ScheduleEvent on status change"
echo "   - EventsChannel() feeds events to dashboard"
echo ""
echo "2. Dashboard Integration:"
echo "   - waitForSmokeTestEvent() listens for events"
echo "   - SmokeTestEventMsg delivered to Update()"
echo "   - applySmokeTestEvent() creates/updates lights"
echo ""
echo "3. View Integration:"
echo "   - View() displays certification lights"
echo "   - Grouped under 'certification' source"
echo "   - Shows status, level %, and event type"
echo ""

echo "Dashboard Update Flow:"
echo "==========================================="
echo ""
echo "  Scheduler"
echo "    ↓"
echo "  Emit ScheduleEvent"
echo "    ↓"
echo "  EventsChannel()"
echo "    ↓"
echo "  waitForSmokeTestEvent()"
echo "    ↓"
echo "  BubbleTeaDashboard.Update(SmokeTestEventMsg)"
echo "    ↓"
echo "  applySmokeTestEvent()"
echo "    ├─ Create cert:{endpointID} light"
echo "    ├─ Map level to status (green/yellow/red/dark)"
echo "    └─ Update details with level % and event type"
echo "    ↓"
echo "  View() renders on next tick"
echo ""

echo "Configuration (cmd/adhd):"
echo "==========================================="
echo ""
echo "To enable scheduler:"
echo ""
echo "  import \"github.com/james-gibson/adhd/internal/smoketest\""
echo ""
echo "  // Create scheduler"
echo "  runner := smoketest.NewRunner(proxyExecutor)"
echo "  scheduler := smoketest.NewScheduler(runner)"
echo ""
echo "  // Register endpoints"
echo "  scheduler.RegisterEndpoint(&smoketest.CertifiedEndpoint{"
echo "    ID: \"stripe-api\","
echo "    URL: \"https://api.stripe.com/mcp\","
echo "    AuthType: \"bearer\","
echo "    Token: os.Getenv(\"STRIPE_TOKEN\"),"
echo "  })"
echo ""
echo "  // Start scheduler"
echo "  scheduler.Start(ctx)"
echo ""
echo "  // Wire to dashboard"
echo "  dashboard.scheduler = scheduler"
echo "  dashboard.testEvents = make(chan smoketest.ScheduleEvent, 100)"
echo ""
echo "  // Feed events to dashboard"
echo "  go func() {"
echo "    for event := range scheduler.EventsChannel() {"
echo "      dashboard.Send(SmokeTestEventMsg{Event: event})"
echo "    }"
echo "  }()"
echo ""

echo "Files Changed:"
echo "==========================================="
echo ""
echo "internal/dashboard/msgs.go"
echo "  + SmokeTestEventMsg type"
echo "  + waitForSmokeTestEvent() function"
echo ""
echo "internal/dashboard/bubbletea.go"
echo "  + scheduler field to BubbleTeaDashboard"
echo "  + testEvents channel"
echo "  + Case for SmokeTestEventMsg in Update()"
echo "  + applySmokeTestEvent() method"
echo ""

echo "What This Unlocks:"
echo "==========================================="
echo ""
echo "✓ Real-time certification display"
echo "✓ Automatic status updates (no polling)"
echo "✓ Visual status indicators (color-coded)"
echo "✓ Event history in details"
echo "✓ Dashboard integration with lights system"
echo "✓ Production-ready foundation"
echo ""

echo "Next Phase 6: Scheduler Initialization & Config"
echo "==========================================="
